config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  namespace :api do
    namespace :v1 do
      resources :comments
      resources :tasks, only: %i[index show create]
    end
  end

  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  namespace :admin do
    root to: 'dashboard#show'
    resources :admins
    resources :tasks, only: %i[index show update] do
      resources :comments, only: :create
    end
    resources :users
    resource :dashboard, :controller => 'dashboard', only: :show
  end

  resources :tasks do
    resources :comments
  end
  resources :users, :controller => 'users', only: %i[show destroy]
  resource :dashboard, :controller => 'dashboard', only: :show
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :tasks
  has_many :comments, as: :author

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :author, polymorphic: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :admin, optional: true
  has_many :comments
  enum status: %i[opened closed]

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, as: :author
  has_many :tasks, dependent: :destroy

  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :set_admin, only: %i[show destroy]

  def index
    @admins = Admin.all
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admin_admin_path(@admin)
    else
      render action: 'new'
    end
  end

  def destroy
    @admin.destroy
    redirect_to(admin_admins_url)
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:email, :password)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :find_task

  # def create
  #   current_admin.comments.create!(comment_params)
  #   redirect_to admin_tasks_path
  # end

  # private

  # def comment_params
  #   params.require(:comment).permit(:task_id, :body)
  # end
  def new
    @comment = Comment.new
  end

  def create
    @comment = @task.comments.build(comment_params)
    if @comment.save
      redirect_to admin_task_path(@task), flash: { notice: 'Comment added successfully' }
    else
      redirect_to admin_task_path(@task), flash: { notice: 'Error while commenting' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :author_type)
          .merge(author_id: current_admin.id)
  end

  def find_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_task, only: %i[show update]

  def index
    @tasks = Task.all
  end

  def update
    if @task.update(status: converted_status)
      redirect_to admin_tasks_path
      flash[:notice] = 'Task has been updated successfully!'
    end
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:status)
  end

  def converted_status
    if %w[1 2].include?(task_params[:status])
      task_params[:status].to_i
    else
      task_params[:status]
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy]

  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    if @user.persisted?
      redirect_to admin_user_url(@user)
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy!
    redirect_to %i[admin users]
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_task

  def new
    @comment = Comment.new
  end

  def create
    @comment = @task.comments.build(comment_params)
    if @comment.save
      redirect_to task_path(@task), flash: { notice: 'Comment added successfully' }
    else
      redirect_to task_path(@task), flash: { notice: 'Error while commenting' }
    end
  end

  def destroy
    if @comment.destroy
      redirect_to task_path(@task)
    else
      redirect_to task_path(@task), flash: { error: 'Something went wrong' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :author_type)
          .merge(author_id: current_user.id)
  end

  def find_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @tasks = current_user.tasks
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:notice] = 'Task has been created'
      redirect_to task_path(@task)
    else
      render 'new'
    end
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Task has been updated successfully!'
      redirect_to task_path(@task)
    else
      flash[:error] = 'Task has not been updated !'
      render 'edit'
    end
  end

  def destroy
    if @task.destroy
      flash[:notice] = 'Task has been deleted successfully!'
    else
      flash[:error] = 'Task has not been deleted'
    end
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :body)
          .merge(user: current_user)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path if @user.destroy
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/v1/tasks_helper.rb
module Api::V1::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/index.html.slim
p#notice
  = notice
.container
  h1[align="center"]
    | Users
  table.table.table-hover
    thead
      tr
        th
          | ID
        th
          | Email
        th
          | Tasks opened
        th
          | Tasks closed
        th
        th
    tbody
      - @users.each do |user|
        tr
          td
            = user.id
          td
            = user.email
          td
            = user.tasks.opened.count
          td
            = user.tasks.closed.count
          td
            = link_to 'Show', admin_user_path(user), class:"btn btn-info btn-sm"
          td
            = link_to 'Destroy', admin_user_path(user),class:"btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' }
  br
  |  <div class="inline", align="center"> 
  = link_to "New User", new_admin_user_path, class:"btn btn-success"
  = link_to "Back", admin_dashboard_path, class:"btn btn-primary"

app/views/admin/users/new.html.slim
.container
  = simple_form_for :user, url: admin_users_path do |f|
    = f.input :email
    = f.input :password
    = f.button :submit, class:"btn btn-success"

app/views/admin/users/show.html.slim
.container
  .well
    h1
      b
        | E-mail: 
      = @user.email
    h2
      b
        | Date of registration: 
      = @user.created_at
    h2
      b
        | Tasks created: 
      = @user.tasks.count
  = link_to "Back", admin_users_path, class:"btn btn-primary btn-lg"
  = link_to 'Destroy', admin_user_path(@user),class:"btn btn-danger btn-lg", method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/show.html.slim
.container
  .well
    h1
      | My e-mail: 
      = current_user.email
    h2
      | Date of registration: 
      = current_user.created_at
    h2
      | Tasks created: 
      = current_user.tasks.count
    p.inline
      = link_to "Delete my profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
      = link_to "My Tasks", dashboard_path, class: "btn btn-info"